spring:
  application:
    name: eureka-service-register
  profiles:
    active: node1
---
spring:
  profiles: node1
server:
  port: 8761

eureka:
  instance:
    hostname: node1
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    serviceUrl:
      #将register1注册到register2上，实现HA
      defaultZone: http://node2:8762/eureka/
---
spring:
  profiles: node2
server:
  port: 8762

eureka:
  instance:
    hostname: node2
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    serviceUrl:
      defaultZone: http://node1:8761/eureka/